const TOGGLE_MODAL = "TOGGLE_MODAL";

const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
const ACTIVE_SIDEBAR = "ACTIVE_SIDEBAR";

const RESIZE_SCREEN = "RESIZE_SCREEN";

const CHANGE_THEME = "CHANGE_THEME";

export { TOGGLE_MODAL, TOGGLE_SIDEBAR, RESIZE_SCREEN, CHANGE_THEME };
